[package]
name = "hring-h2spec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
hring = { version = "0.1.0", path = "../../crates/hring" }
tokio = { version = "1.23.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
which = "4.4.0"

[profile.dev.package."*"]
opt-level = 2