[profile.default]
slow-timeout = { period = "5s", terminate-after = 3 }

[profile.miri]
slow-timeout = { period = "60s", terminate-after = 5 }

[profile.ci]
slow-timeout = { period = "5s", terminate-after = 6 }